ForumRoulette/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from ForumRoulette import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('posts.urls')),
    path('user/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('popular/', views.popular, name='popular'),
    path('post_list/<str:username>/', views.post_list, name='user_posts_list'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('create/', views.create_post, name='create'),
    path('<int:post_id>/vote/', views.vote, name='vote'),
    path('<int:post_id>/vote/<int:is_down_vote>/', views.vote, name='vote'),
    path('<int:post_id>/down_vote/', views.down_vote, name='down_vote'),
    path('<int:comment_id>/vote/comment/<int:is_down_vote>', views.vote_comment, name='vote_comment'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('random/', views.random_comment, name='random'),
    path('search/', views.search, name='search')
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('profile_picture/', views.change_profile_picture, name='profile_picture'),
    path('', views.index, name='index'),
    path('<str:username>/', views.profile, name='profile'),
]

users/models.py
from django.contrib.auth.models import User as SystemUser
from django.db import models
from posts.models import Post


# class User(models.Model):   # TestUser: Test | TestPassword123
#     username = models.CharField(max_length=50)
#     email = models.EmailField()
#     password = 'How do I do this?!?'
#     create_date = models.DateTimeField('date created')
#     post_count = models.IntegerField(default=0)
#
#     def __str__(self):
#         return self.username


class UserInfo(models.Model):
    user_reference = models.ForeignKey(SystemUser, on_delete=models.CASCADE)
    post_count = models.IntegerField(default=0)
    random_post = models.ForeignKey(Post, blank=True, null=True, on_delete=models.DO_NOTHING)
    xp = models.IntegerField(default=100)
    profile_picture = models.ImageField(upload_to='profilePictures/', blank=True)

    def __str__(self):
        return self.user_reference.username

    def posts_available(self):
        total_posts = int((self.xp / 100) // 1)  # Gets maximum possible posts from current XP
        posts_available_count = total_posts - self.post_count
        if posts_available_count > 0:
            return posts_available_count
        else:
            return 0

    def xp_modulo(self):
        return self.xp % 100

users/forms.py
from django import forms


class UserCreationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=50)
    password = forms.PasswordInput()
    email = forms.EmailField()


class ProfilePictureForm(forms.Form):
    profile_picture = forms.ImageField(label='Profile Picture')

users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User

from .models import UserInfo
from .forms import ProfilePictureForm


def index(request):
    return HttpResponse("Hello, world. You're at the users index.")


def profile(request, username):
    current_user = get_object_or_404(User, username=username)
    user_info = get_object_or_404(UserInfo, user_reference=current_user.id)
    return render(request, 'profile.html', {'selected_user': current_user, 'user_info': user_info})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            user_info = UserInfo(user_reference=user)
            user_info.save()
            return redirect('posts:index')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def change_profile_picture(request):
    if request.method == 'POST':
        form = ProfilePictureForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            user_info = get_object_or_404(UserInfo, user_reference=current_user.id)
            user_info.profile_picture = form.cleaned_data['profile_picture']
            user_info.save()
            return render(request, 'profile.html', {'selected_user': current_user, 'user_info': user_info})
    else:
        form = ProfilePictureForm()
    return render(request, 'profile_picture.html', {'form': form})

users/templates/profile.html
{% extends 'base_generic.html' %}

{% block title %}<title>{{ selected_user.username }}</title>{% endblock %}

{% block content %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <div class="userinformation">
    <div class="userheader">
        {% if user_info.profile_picture %}
            <img src="{{ user_info.profile_picture.url }}" class="profilepicture" alt="Error Picture not found">
        {% endif %}
        <h2>{{ selected_user.username }}</h2>
    </div>

        <div class="outer">
            <div class="xp-bar" style="width:{{ user_info.xp_modulo }}%">{{ user_info.xp_modulo }}XP</div>
        </div>

    </div>
    <p>Created: {{ selected_user.date_joined.date }}</p>
    <a class="userposts" href="{% url "posts:user_posts_list" selected_user.username %}">Post Count: {{ user_info.post_count }}</a>
    {% if user.is_authenticated %}
        <p>Posts available: {{ user_info.posts_available }}</p>
        <p>Random Post: {{ user_info.random_post }}</p>
    {% endif %}
    {% if selected_user == request.user %}
        <a class="changeProfilPicture"href="{% url "users:profile_picture" %}">Change your profile picture</a>
    {% endif %}

{% endblock %}

users/templates/profile_picture.html
{% extends "base_generic.html" %}

{% block title %}<title>Change your profile picture</title>{% endblock %}

{% block content %}
    <form method="post" action="{% url 'users:profile_picture' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit"/>
    </form>
{% endblock %}

users/templates/signup.html
{% extends 'base_generic.html' %}

{% block content %}
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}