ForumRoulette/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from ForumRoulette import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('posts.urls')),
    path('user/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('popular/', views.popular, name='popular'),
    path('post_list/<str:username>/', views.post_list, name='user_posts_list'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('create/', views.create_post, name='create'),
    path('<int:post_id>/vote/', views.vote, name='vote'),
    path('<int:post_id>/vote/<int:is_down_vote>/', views.vote, name='vote'),
    path('<int:post_id>/down_vote/', views.down_vote, name='down_vote'),
    path('<int:comment_id>/vote/comment/<int:is_down_vote>', views.vote_comment, name='vote_comment'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('random/', views.random_comment, name='random'),
    path('search/', views.search, name='search')
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('profile_picture/', views.change_profile_picture, name='profile_picture'),
    path('', views.index, name='index'),
    path('<str:username>/', views.profile, name='profile'),
]

posts/models.py
import datetime
import random
from random import randint

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):
    creator = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=0)
    post_title = models.CharField(max_length=200)
    post_text = models.CharField(max_length=500)
    pub_date = models.DateTimeField('date published')
    # up_votes = models.IntegerField(default=0)
    # down_votes = models.IntegerField(default=0)
    up_votes_list = models.ManyToManyField(User, related_name='vote_list', blank=True)
    down_votes_list = models.ManyToManyField(User, related_name='down_votes_list', blank=True)
    post_image = models.ImageField(blank=True)

    def __str__(self):
        return self.post_title

    def time_since_published(self):
        return timezone.now() - self.pub_date

    def up_vote_count(self):
        return self.up_votes_list.count()

    def down_vote_count(self):
        return self.down_votes_list.count()

    def pub_date_printable(self):
        if timezone.now().year - self.pub_date.year > 0:
            return "over " + str(timezone.now().year - self.pub_date.year) + " year(s) ago"
        if timezone.now().month - self.pub_date.month > 0:
            return "over " + str(timezone.now().month - self.pub_date.month) + " month(s) ago"
        if timezone.now().day - self.pub_date.day > 6:
            return str(int(timezone.now().day - self.pub_date.day / 7)) + " week(s) ago"
        if timezone.now().day - self.pub_date.day > 0:
            return str(timezone.now().day - self.pub_date.day) + " day(s) ago"
        if timezone.now().hour - self.pub_date.hour > 0:
            return str(timezone.now().hour - self.pub_date.hour) + " hour(s) ago"
        if timezone.now().minute - self.pub_date.minute > 0:
            return str(timezone.now().minute - self.pub_date.minute) + " minute(s) ago"
        else:
            return "just now"

    def vote_difference(self):
            return self.up_vote_count() - self.down_vote_count()

    # def random(self):
    #     all_posts = self.id.
    #     return random.choice(all_posts)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.DO_NOTHING, default=0)
    comment_text = models.CharField(max_length=500)
    pub_date = models.DateTimeField('date published')
    # up_votes = models.IntegerField(default=0)
    # down_votes = models.IntegerField(default=0)
    up_votes_list = models.ManyToManyField(User, related_name='comment_vote_list', blank=True)
    down_votes_list = models.ManyToManyField(User, related_name='comment_down_vote_list', blank=True)

    def __str__(self):
        return self.comment_text

    def up_vote_count(self):
        return self.up_votes_list.count()

    def down_vote_count(self):
        return self.down_votes_list.count()

    def vote_difference(self):
            return self.up_vote_count() - self.down_vote_count()

    def pub_date_printable(self):
        if timezone.now().year - self.pub_date.year > 0:
            return "over " + str(timezone.now().year - self.pub_date.year) + " year(s) ago"
        if timezone.now().month - self.pub_date.month > 0:
            return "over " + str(timezone.now().month - self.pub_date.month) + " month(s) ago"
        if timezone.now().day - self.pub_date.day > 6:
            return str(int(timezone.now().day - self.pub_date.day / 7)) + " week(s) ago"
        if timezone.now().day - self.pub_date.day > 0:
            return str(timezone.now().day - self.pub_date.day) + " day(s) ago"
        if timezone.now().hour - self.pub_date.hour > 0:
            return str(timezone.now().hour - self.pub_date.hour) + " hour(s) ago"
        if timezone.now().minute - self.pub_date.minute > 0:
            return str(timezone.now().minute - self.pub_date.minute) + " minute(s) ago"
        else:
            return "just now"

users/models.py
from django.contrib.auth.models import User as SystemUser
from django.db import models
from posts.models import Post


# class User(models.Model):   # TestUser: Test | TestPassword123
#     username = models.CharField(max_length=50)
#     email = models.EmailField()
#     password = 'How do I do this?!?'
#     create_date = models.DateTimeField('date created')
#     post_count = models.IntegerField(default=0)
#
#     def __str__(self):
#         return self.username


class UserInfo(models.Model):
    user_reference = models.ForeignKey(SystemUser, on_delete=models.CASCADE)
    post_count = models.IntegerField(default=0)
    random_post = models.ForeignKey(Post, blank=True, null=True, on_delete=models.DO_NOTHING)
    xp = models.IntegerField(default=100)
    profile_picture = models.ImageField(upload_to='profilePictures/', blank=True)

    def __str__(self):
        return self.user_reference.username

    def posts_available(self):
        total_posts = int((self.xp / 100) // 1)  # Gets maximum possible posts from current XP
        posts_available_count = total_posts - self.post_count
        if posts_available_count > 0:
            return posts_available_count
        else:
            return 0

    def xp_modulo(self):
        return self.xp % 100

posts/forms.py
from django import forms


class CreatePostForm(forms.Form):
    post_title = forms.CharField(label='Post Title', max_length=200)
    post_text = forms.CharField(widget=forms.Textarea, label='Post Text', max_length=500)
    post_image = forms.ImageField(label='Post Image (optional)', required=False)


class CreateCommentForm(forms.Form):
    comment_text = forms.CharField(widget=forms.Textarea, label='Comment Text', max_length=500)

posts/views.py
import os
import random

from django.conf import settings

from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.files.storage import default_storage
from django.utils import timezone

from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect

from .models import Post, Comment
from .forms import CreatePostForm, CreateCommentForm
from users.models import UserInfo, SystemUser


def not_admin_check(user):
    return not user.username == 'admin'


def can_post_check(user):
    user_info = get_object_or_404(UserInfo, pk=user.id)
    if user_info.posts_available() <= 1:
        return True
    else:
        return False


# def can_comment_check(user, post_id):
#     current_user = user.username
#     user_info = get_object_or_404(UserInfo, user_reference=current_user.username)
#     current_post = get_object_or_404(Post, pk=post_id)
#     if user_info.random_post == current_post:
#         return True
#     else:
#         return False


def has_already_voted(current_post, current_user):
    if current_post.up_votes_list.filter(username=current_user.username).exists():
        return 1
    else:
        return 0


def has_already_down_voted(current_post, current_user):
    if current_post.down_votes_list.filter(username=current_user.username).exists():
        return 1
    else:
        return 0


def has_already_voted_comment(current_comment, current_user):
    if current_comment.up_votes_list.filter(username=current_user.username).exists():
        return 1
    else:
        return 0


def has_already_down_voted_comment(current_comment, current_user):
    if current_comment.down_votes_list.filter(username=current_user.username).exists():
        return 1
    else:
        return 0


def image_upload(request):
    save_path = os.path.join(settings.MEDIA_ROOT, 'uploads', request.FILES['file'])
    path = default_storage.save(save_path, request.FILES['file'])
    # document = Document.objects.create(document=path, upload_by=request.user)
    return default_storage.path(path)


def index(request):
    latest_posts_list = Post.objects.order_by('-pub_date')[:30]
    context = {
        'post_list': latest_posts_list,
    }
    return render(request, 'index.html', context)


def popular(request):
    # popular_posts_list = Post.objects.order_by('vote_difference')[:30]  # Cannot sort by model methods
    posts_list = Post.objects.all()
    popular_posts_list = sorted(posts_list, key=lambda votes: -(votes.up_votes_list.count()))[:30]
    # popular_posts_list = Post.objects.all()[:10]
    context = {
        'post_list': popular_posts_list,
    }
    return render(request, 'index.html', context)


def post_list(request, username):
    user = get_object_or_404(SystemUser, username=username)
    posts_list = Post.objects.all()
    user_posts_list = posts_list.filter(creator=user).order_by('-pub_date')
    context = {
        'post_list': user_posts_list,
    }
    return render(request, 'index.html', context)


def post(request, post_id):
    return HttpResponse("You're looking at the post with id %i" % post_id)


def detail(request, post_id):
    current_post = get_object_or_404(Post, pk=post_id)
    current_user = request.user
    has_voted = has_already_voted(current_post, current_user)
    has_down_voted = has_already_down_voted(current_post, current_user)
    return render(request, 'detail.html',
                  {'post': current_post, 'has_voted': has_voted, 'has_down_voted': has_down_voted})


@login_required
@user_passes_test(not_admin_check, login_url='/ADMINS_CANT_CREATE_POSTS/')
@user_passes_test(can_post_check, login_url='/NOT_ENOUGH_XP/')
def create_post(request):
    if request.method == 'POST':
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            # image_path = image_upload(request)
            p = Post(creator=current_user, post_title=form.cleaned_data['post_title'],
                     post_text=form.cleaned_data['post_text'], pub_date=timezone.now(),
                     post_image=form.cleaned_data['post_image'])
            p.save()
            user_info = get_object_or_404(UserInfo, user_reference=current_user)
            user_info.post_count += 1
            user_info.save()
            return redirect('posts:detail', p.id)
    else:
        form = CreatePostForm()
    return render(request, 'createPost.html', {'form': form})


@login_required
def vote(request, post_id, is_down_vote=0):
    current_post = get_object_or_404(Post, pk=post_id)
    current_user = request.user
    post_creator = get_object_or_404(SystemUser, id=current_post.creator.id)
    creator_info = get_object_or_404(UserInfo, user_reference=post_creator.id)
    has_already_voted_check = has_already_voted(current_post, current_user)
    has_already_down_voted_check = has_already_down_voted(current_post, current_user)
    if not is_down_vote:
        if not has_already_voted_check:
            if has_already_down_voted_check:
                current_post.down_votes_list.remove(current_user)
                creator_info.xp += 5
            current_post.up_votes_list.add(current_user)
            creator_info.xp += 5
        else:
            current_post.up_votes_list.remove(current_user)
            creator_info.xp -= 5
    else:
        if not has_already_down_voted_check:
            if has_already_voted_check:
                current_post.up_votes_list.remove(current_user)
                creator_info.xp -= 5
            current_post.down_votes_list.add(current_user)
            creator_info.xp -= 5
        else:
            current_post.down_votes_list.remove(current_user)
            creator_info.xp += 5
    creator_info.save()
    return redirect('posts:detail', current_post.id)


@login_required
def down_vote(request, post_id):
    is_down_vote = 1
    return redirect('posts:vote', post_id, is_down_vote)


@login_required
def vote_comment(request, comment_id, is_down_vote):
    current_comment = get_object_or_404(Comment, pk=comment_id)
    current_post = get_object_or_404(Post, pk=current_comment.post.id)
    current_user = request.user
    comment_creator = get_object_or_404(SystemUser, id=current_comment.creator.id)
    creator_info = get_object_or_404(UserInfo, user_reference=comment_creator.id)
    has_already_voted_check = has_already_voted_comment(current_comment, current_user)
    has_already_down_voted_check = has_already_down_voted_comment(current_comment, current_user)
    if not is_down_vote:
        if not has_already_voted_check:
            if has_already_down_voted_check:
                current_comment.down_votes_list.remove(current_user)
                creator_info.xp += 5
            current_comment.up_votes_list.add(current_user)
            creator_info.xp += 5
        else:
            current_comment.up_votes_list.remove(current_user)
            creator_info.xp -= 5
    else:
        if not has_already_down_voted_check:
            if has_already_voted_check:
                current_comment.up_votes_list.remove(current_user)
                creator_info.xp -= 5
            current_comment.down_votes_list.add(current_user)
            creator_info.xp -= 5
        else:
            current_comment.down_votes_list.remove(current_user)
            creator_info.xp += 5
    creator_info.save()
    return redirect('posts:detail', current_post.id)


@login_required
# @user_passes_test(can_comment_check(post_id), login_url='YOU_CANT_COMMENT_ON_THIS_POST')
def create_comment(request, post_id):  # Create permissions
    current_post = get_object_or_404(Post, pk=post_id)
    current_user = request.user
    user_info = get_object_or_404(UserInfo, user_reference=current_user.id)
    if user_info.random_post == current_post:
        if request.method == 'POST':
            form = CreateCommentForm(request.POST)
            if form.is_valid():
                comment = Comment(post=current_post, creator=current_user,
                                  comment_text=form.cleaned_data['comment_text'],
                                  pub_date=timezone.now())
                comment.save()
                user_info.random_post = None
                user_info.xp += 20
                user_info.save()
                return redirect('posts:detail', current_post.id)
        else:
            form = CreateCommentForm()
        return render(request, 'createComment.html', {'form': form, 'post': current_post})
    else:
        return HttpResponse("You are not allowed to comment on this post.")


def random_comment(request):
    current_user = request.user
    user_info = get_object_or_404(UserInfo, user_reference=current_user.id)
    if user_info.random_post is None:
        all_posts = Post.objects.all()
        random_post = random.choice(all_posts)
        random_id = random_post.id
        user_info.random_post = random_post
        user_info.save()
        return redirect('posts:detail', random_id)
    else:
        return redirect('posts:detail', user_info.random_post.id)


def search(request):
    query = request.GET['search_term']
    search_posts_list = Post.objects.filter(post_title__contains=query)
    context = {
        'post_list': search_posts_list,
    }
    return render(request, 'index.html', context)

posts/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>ForumRoulette</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">
            {% block sidebar %}
                <ul class="sidebar-nav">
                    <li><a href="{% url 'posts:index' %}">Home</a></li>
                    <li><a href="{% url 'posts:index' %}">Popular Posts</a></li>
                    <li><a href="{% url 'posts:create' %}">Create Post</a></li>
                </ul>
                <ul class="sidebar-nav">

                    ...

                    {% if user.is_authenticated %}
                        <li>User: {{ user.get_username }}</li>
                        <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                    {% endif %}
                </ul>
            {% endblock %}
        </div>
        <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
</div>
</body>
</html>

posts/templates/createComment.html
{% extends "base_generic.html" %}

{% block title %}<title>Create a Comment</title>{% endblock %}

{% block content %}
    <form method="post" action="{% url 'posts:comment' post.id %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit"/>
    </form>
{% endblock %}

posts/templates/createPost.html
{% extends "base_generic.html" %}

{% block title %}<title>Create a Post</title>{% endblock %}

{% block content %}
    <form method="post" action="{% url 'posts:create' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit"/>
    </form>
{% endblock %}

posts/templates/detail.html
{% extends 'base_generic.html' %}

{% block title %}<title>{{ post.post_title }}</title>{% endblock %}

{% block content %}

    <div class="comment">

        <div class="voting-section">
            <a class="fas fa-angle-up like" href="{% url 'posts:vote' post.id %}" id="like"></a>
            {% if has_voted == 1 %}
                <script>
                    likepost()
                </script>
            {% endif %}
            <div class="score upvote hide">{{ post.up_vote_count }}</div>
            <div class="score downvote hide">{{ post.down_vote_count }}</div>
            <div class="score likes">{{ post.vote_difference }}</div>
            <a class="fas fa-angle-down  dislike" href="{% url 'posts:down_vote' post.id %}" id="dislike"></a>
            {% if has_down_voted == 1 %}
                <script>
                    dislikepost()
                </script>
            {% endif %}
        </div>

        <div class="link">
            <h3>{{ post.post_title }}</h3>
            <p>{{ post.post_text }}</p>
                {% if post.post_image %}
                    <img src="{{ post.post_image.url }} " alt="Error picture not found" class="responsive">
                {% endif %}

            <p>Posted: {{ post.pub_date_printable }}</p>
            <a class="profillink" href="{% url 'users:profile' post.creator %}">Posted by {{ post.creator }}</a>
            {% for userinfo in user.userinfo_set.all %}
                {% if userinfo.random_post == post %}
                    <div class="addComment">
                        <a href="{% url 'posts:comment' post.id %}"> Add comment</a>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

    </div>
    <hr>
    <div class="commentblock">
        {% for comment in post.comment_set.all %}
            <div class="comment">
                <div class="voting-section">
                    <a class="fas fa-angle-up like" href="{% url 'posts:vote_comment' comment.id 0 %}"
                       id="like_comment_{{ forloop.counter }}"></a>
                    {% for voter in comment.up_votes_list.all %}
                        {% if voter.username == user.username %}
                            <script>
                                likeComment({{ forloop.parentloop.counter }})
                            </script>
                        {% endif %}
                    {% endfor %}
                    <div class="score upvote hide">{{ comment.up_vote_count }}</div>
                    <div class="score downvote hide">{{ comment.down_vote_count }}</div>
                    <div class="score likes">{{ comment.vote_difference }}</div>
                    <a class="fas fa-angle-down  dislike" href="{% url 'posts:vote_comment' comment.id 1 %}"
                       id="dislike_comment_{{ forloop.counter }}"></a>
                    {% for voter in comment.down_votes_list.all %}
                        {% if voter.username == user.username %}
                            <script>
                                dislikeComment({{ forloop.parentloop.counter }})
                            </script>
                        {% endif %}
                    {% endfor %}
                </div>

                <div>
                    <a class="profillink" href="{% url 'users:profile' comment.creator %}">{{ comment.creator }}</a>
                    <p>Posted: {{ comment.pub_date_printable }}</p>
                    <p>{{ comment.comment_text }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

posts/templates/index.html
{% extends "base_generic.html" %}
{# TODO Get Voting Working, comments count, design#}
{% block content %}
    {% if post_list %}
        {% load static %}

        <link rel="stylesheet" href="{% static 'css/postStyle.css' %}">
        <ul id="posts">
            {% for post in post_list %}
                <li id="post_content" onclick=window.location.href="{% url 'posts:detail' post.id %}">

                    <div class="voting-section">
                        <a class="fas fa-angle-up like" id="like_{{ forloop.counter }}"
                           href="{% url 'posts:vote' post.id %}"></a>
                        {% for voter in post.up_votes_list.all %}
                            {% if voter.username == user.username %}
                                <script>
                                    like({{ forloop.parentloop.counter }})
                                </script>
                            {% endif %}
                        {% endfor %}
                        <div class="score dislikes hide">{{ post.up_vote_count }}</div>
                        <div class="score unvoted hide">{{ post.down_vote_count }}</div>
                        <div class="score likes">{{ post.vote_difference }}</div>
                        <a class="fas fa-angle-down  dislike" id="dislike_{{ forloop.counter }}"
                           href="{% url 'posts:down_vote' post.id %}"></a>
                        {% for voter in post.down_votes_list.all %}
                            {% if voter.username == user.username %}
                                <script>
                                    dislike({{ forloop.parentloop.counter }})
                                </script>
                            {% endif %}
                        {% endfor %}
                    </div>


                    <div class="link">
                        <h3>{{ post.post_title }}</h3>
                        <a href="{% url 'posts:detail' post.id %}" class="text">{{ post.post_text }}</a>
                        <div class="information ">
                            <a class="profillink"href="{% url 'users:profile' post.creator %}">Posted by {{ post.creator }} {{ post.pub_date_printable }}</a>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No posts are available.</p>
    {% endif %}

{% endblock %}