ForumRoulette/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from ForumRoulette import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('posts.urls')),
    path('user/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('popular/', views.popular, name='popular'),
    path('post_list/<str:username>/', views.post_list, name='user_posts_list'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('create/', views.create_post, name='create'),
    path('<int:post_id>/vote/', views.vote, name='vote'),
    path('<int:post_id>/vote/<int:is_down_vote>/', views.vote, name='vote'),
    path('<int:post_id>/down_vote/', views.down_vote, name='down_vote'),
    path('<int:comment_id>/vote/comment/<int:is_down_vote>', views.vote_comment, name='vote_comment'),
    path('<int:post_id>/comment/', views.create_comment, name='comment'),
    path('random/', views.random_comment, name='random'),
    path('search/', views.search, name='search')
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('profile_picture/', views.change_profile_picture, name='profile_picture'),
    path('', views.index, name='index'),
    path('<str:username>/', views.profile, name='profile'),
]

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>ForumRoulette</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css"
          integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static "js/sidenavigation.js" %}"></script>
    <script src="{% static "js/vote.js" %}"></script>

</head>
<body>

<header>
    <div class="header-item left">
        <img src="{% static 'Images/dice.gif' %}"  alt="Error 404" class="randomImage">
        <a href="{% url 'posts:index' %} " class="header-item">Random Roulette </a>
    </div>
   <div class="mediahide header-item right ">
        <form action="{% url 'posts:search' %}" method="get">
            {% csrf_token %}
            <div class="searchContainer">
                <i class="fa fa-search left-icon"></i>
                <input type="search" class="searchbar" placeholder="Search Random Roulette" value="{{ query }}"
                       name="search_term" required/>

            </div>
        </form>

    </div>

</header>


<main>

    <aside>
        <nav class="topnav">
            <a href="#" onclick="openNav()">
                <svg width="30" height="30" id="icoOpen">
                    <path d="M0,5 30,5" stroke="#000" stroke-width="5"/>
                    <path d="M0,14 30,14" stroke="#000" stroke-width="5"/>
                    <path d="M0,23 30,23" stroke="#000" stroke-width="5"/>
                </svg>
            </a>
        </nav>

        <div id="sideNavigation" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <ul>
                <li><a href="{% url 'posts:index' %}" class="fas fa-home"> <p>Home</p></a></li>
                <li><a href="{% url 'posts:popular' %}" class="fab fa-hotjar"> <p>Popular Posts</p></a></li>
                <li><a href="{% url 'posts:create' %}" class="far fa-paper-plane"> <p>Create Post</p></a></li>
            </ul>
            <ul>
                {% if user.is_authenticated %}
                    <a href="{% url 'posts:random' %}" class="fas fa-dice"> <p>Random</p></a>
                    <hr>
                    <li><a href="{% url 'users:profile' user.username %}">Username: {{ user.username }}</a></li>
                    <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                    <li><a href="{% url 'users:signup' %}?next={{ request.path }}">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>


    </aside>


    <div class="content" id="content">
        <div class="wrapper ">
            {% block content %}
            {% endblock %}
        </div>

        {% comment %}        <footer class="footer">
            <p>footer</p>
        </footer>{% endcomment %}


    </div>


</main>

</body>
</html>